# CSCI-220 Group Project: Random Password Generator
# Authors: Daniel Roberts, Caleb (lastname), Griffin (lastname)
# (Due Date)
# Course: CSCI-220-03-04
# Instructor: Dr. Mia Wang
# We certify that this project is entirely of our own collaborative work, with work shared through GitHub.

# The purpose of this program is to generate a randomized password
# depending on parameters such as the password's length, whether
# they wish to include special characters, and more. The password
# will resemble something like that of one generated by Google or Edge's
# "suggested password" feature when creating new online accounts.

import random
from time import sleep


def password_generator():
    """Generates a randomized password based on user-defined parameters."""

    # Validate password length
    while True:
        try:
            password_length_input = int(input("How long would you like your password to be? "))
            if password_length_input < 4:
                print("\nPassword length must be greater than 3.\n")
                continue
            break
        except ValueError:
            print("\nInvalid input. Please enter a valid integer.\n")

    print()
    sleep(1)

    # Validate special character preference
    while True:
        specify_special_chars = input("Would you like to use special characters? Respond with either \"Yes\" or \"No\": ").strip().lower()

        if specify_special_chars in ("yes", "no"):
            break
        else:
            print("\nInvalid input. Please respond with either \"Yes\" or \"No\".\n")

    print()
    sleep(1)

    # Character sets
    ascii_list = [chr(i) for i in range(32, 127)] # All printable ASCII characters
    alphanumerical_list = [char for char in ascii_list if char.isalnum()] # Only letters and digits
    special_characters_list = ["!", "?", "$", "@", "#", "_"] # Defined special characters

    # Build initial password list
    password_chars = [random.choice(alphanumerical_list) for _ in range(password_length_input)]

    # Insert special character randomly if requested
    if specify_special_chars == "yes":
        special_chars_insert_index = random.randint(0, len(password_chars) - 1)
        password_chars[special_chars_insert_index] = random.choice(special_characters_list)

    # Combine characters into a single string
    password_result = ("").join(password_chars)

    print(f"Your unique password: {password_result}\n")


if __name__ == "__main__":
    print("\nWelcome to the Random Password Generator!\n")
    sleep(1)

    while True:
        password_generator()
        sleep(1)

        # Validation loop for "Generate another?" prompt
        while True:
            do_again = input("Generate another? ").strip().lower()
            print()
            if do_again in ("yes", "y", "sure"):
                sleep(1)
                break # Exit inner loop and run password_generator() again
            elif do_again in ("no", "n", "nope"):
                sleep(1)
                print("Thank you for using the Random Password Generator! Goodbye.")
                exit()
            else:
                print("Invalid input. Please respond with either \"Yes\" or \"No\".\n")
