# CSCI-220 Group Project: Random Password Generator
# Authors: Daniel Roberts, Caleb (lastname), Griffin (lastname)
# (Due Date)
# Course: CSCI-220-03-04
# Instructor: Dr. Mia Wang
# We certify that this project is entirely of our own collaborative work.

""" The purpose of this program is to generate a randomized password
    depending on parameters such as the password's length, whether
    they wish to include special characters, and more. The password
    will resemble something like that of one generated by Google or Edge's
    "suggested password" feature when creating new online accounts. """

def password_generator():
    """ If you can find a way to use ASCII numbers and exclude the non-compatible characters then please do so, it'll be much more clean """
    
    # List to contain all characters
    main_char_list = ["A", "a", "B", "b", "C", "c", "D", "d", "E", "e", "F", "f", "G", "g", "H", "h", "I", "i", "J", "j", "K", "k", "L", "l", "M", "m", "N", "n", "O", "o", "P", "p", "Q", "q" "R", "r", "S", "s", "T", "t", "U", "u", "V", "v", "W", "w", "X", "x", "Y", "y", "Z", "z", "0", "1", "2", "3", "4", "5", "6" "7", "8", "9"]

    
    print(main_char_list)
    
    
def main():
    password_generator()
    
main()

